import { Field, Float, InputType, Int, ObjectType } from '@nestjs/graphql';
import { Attachment } from 'src/module/common/entities/attachment.entity';
import { EventSettings } from './event-settings.entity';
import { SeoSettings } from './seo-settings.entity';
import { GoogleSettings } from './google-settings.entity';
import { FacebookSettings } from './facebook-settings.entity';
import { ContactDetails } from './contact-details.entity';
import { CurrencyOptions } from './currency-options.entity';
import { PaymentGateway } from './payment-gateway.entity';
import { ServerInfo } from './server-info.entity';
import { AllInput } from './push-notification.entity';
import { Maintenance } from './maintenance.entity';
import { PromoPopup } from './promo-popup.entity';
import { ReviewSystem } from './review-system.entity';
import { DeliveryTime } from './delivery-time.entity';

@InputType('SettingsOptionsInputType', { isAbstract: true })
@ObjectType()
export class SettingsOptions {
  @Field({ nullable: true }) siteTitle?: string;
  @Field({ nullable: true }) siteSubtitle?: string;
  @Field({ nullable: true }) currency?: string;
  @Field({ nullable: true }) minimumOrderAmount?: number;
  @Field(() => Int, { nullable: true }) currencyToWalletRatio?: number;
  @Field(() => Int, { nullable: true }) signupPoints?: number;
  @Field(() => [DeliveryTime], { nullable: true }) deliveryTime?: DeliveryTime[];
  @Field(() => Attachment, { nullable: true }) logo?: Attachment;
  @Field({ nullable: true }) useCashOnDelivery?: boolean;
  @Field({ nullable: true }) freeShipping?: boolean;
  @Field({ nullable: true }) freeShippingAmount?: number;
  @Field({ nullable: true }) taxClass?: string;
  @Field({ nullable: true }) shippingClass?: string;
  @Field(() => SeoSettings, { nullable: true }) seo?: SeoSettings;
  @Field(() => GoogleSettings, { nullable: true }) google?: GoogleSettings;
  @Field(() => FacebookSettings, { nullable: true }) facebook?: FacebookSettings;
  @Field(() => ContactDetails, { nullable: true }) contactDetails?: ContactDetails;
  @Field({ nullable: true }) useOtp?: boolean;
  @Field({ nullable: true }) useGoogleMap?: boolean;
  @Field({ nullable: true }) maximumQuestionLimit?: number;
  @Field({ nullable: true }) useMustVerifyEmail?: boolean;
  @Field({ nullable: true }) maxShopDistance?: number;
  @Field({ nullable: true }) useEnableGateway?: boolean;
  @Field({ nullable: true }) useAi?: boolean;
  @Field({ nullable: true }) isProductReview?: boolean;
  @Field({ nullable: true }) StripeCardOnly?: boolean;
  @Field({ nullable: true }) guestCheckout?: boolean;
  @Field({ nullable: true }) defaultPaymentGateway?: string;
  @Field(() => CurrencyOptions, { nullable: true }) currencyOptions?: CurrencyOptions;
  @Field(() => [PaymentGateway], { nullable: true }) paymentGateway?: PaymentGateway[];
  @Field(() => ServerInfo, { nullable: true }) server_info?: ServerInfo;
  @Field(() => EventSettings, { nullable: true }) smsEvent?: EventSettings;
  @Field(() => EventSettings, { nullable: true }) emailEvent?: EventSettings;
  @Field(() => Attachment, { nullable: true }) collapseLogo?: Attachment;
  @Field({ nullable: true }) enableTerms?: boolean;
  @Field(() => AllInput, { nullable: true }) pushNotification?: AllInput;
  @Field({ nullable: true }) defaultAi?: string;
  @Field({ nullable: true }) siteLink?: string;
  @Field({ nullable: true }) copyrightText?: string;
  @Field({ nullable: true }) externalText?: string;
  @Field({ nullable: true }) externalLink?: string;
  @Field({ nullable: true }) isUnderMaintenance?: boolean;
  @Field(() => Maintenance, { nullable: true }) maintenance?: Maintenance;
  @Field({ nullable: true }) enableCoupons?: boolean;
  @Field({ nullable: true }) isPromoPopUp?: boolean;
  @Field(() => PromoPopup, { nullable: true }) promoPopup?: PromoPopup;
  @Field({ nullable: true }) enableReviewPopup?: boolean;
  @Field(() => ReviewSystem, { nullable: true }) reviewSystem?: ReviewSystem;
  @Field({ nullable: true }) enableEmailForDigitalProduct?: boolean;
  @Field({ nullable: true }) isMultiCommissionRate?: boolean;
}
